eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8182
spring:
  application:
    name: service-cuentas
#  date:
#    mongodb:
#      host: 192.168.8.17
#      port: 27017