server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://192.168.18.11:8761/eureka/
spring:
  application:
    name: service-client
#  date:
#    mongodb:
#      host: 192.168.8.17
#      port: 27017
