server:
  port: 8084
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://192.168.18.11:8761/eureka
spring:
  application:
    name: service-activeaccounts