eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.8.17:8761/eureka/

server:
  port: 8180
spring:
  application:
    name: service-client
#  date:
#    mongodb:
#      host: 192.168.8.17
#      port: 27017
